[package]
name = "robot-simulation-app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy-inspector-egui = "0.28.1"
bevy_egui = "0.31.1" #
bevy_flycam = "0.15.0"
bevy_rapier3d = { version = "0.28.0", features = ["serde-serialize"] }
bevy_salva3d = { path = "../bevy_salva/bevy_salva3d", features = ["rapier"] }
parking_lot = "0.12.3"
rfd = "0.15.2"
rapier3d-urdf = { version = "0.3.0", features = ["stl"] }
nalgebra = "0.33.2"
bincode = "1.3.3"

[dependencies.k]
git = "https://github.com/nsjvidana/k.git"
rev = "978e01f"
version = "0.32.0"

[profile.dev.package."*"]
opt-level = 3

#[profile.dev]
#opt-level = 1
